Changes in social media icons, select network and wallet fields
Synthetify/synthetify-webapp pull request #163
Opened 2021-10-01 11:11 UTC by Kimi82

2021-10-01 11:55 UTC, awojciak commented on src/static/icons.ts
> +  Testnet: mainnet,
Mainnet

2021-10-01 11:55 UTC, awojciak commented on src/static/icons.ts
> +  Localnet: devnet
Devnet

2021-10-01 15:27 UTC, awojciak reviewed
adjust hamburger menu to mockups

2021-10-01 15:33 UTC, awojciak reviewed
![obraz](https://user-images.githubusercontent.com/48929607/135647708-fad29524-3b30-4a12-ac43-aecddc85a981.png)
I think bottom padding of this modal should be smaller

2021-10-03 19:22 UTC, Kimi82 commented
> adjust hamburger menu to mockups

You mean, i need to change mobile hamburger menu?
If so, I haven't done it yet because I can't find the changes in the mockups :/

2021-10-04 05:41 UTC, awojciak commented
> > adjust hamburger menu to mockups
> 
> You mean, i need to change mobile hamburger menu? If so, I haven't done it yet because I can't find the changes in the mockups :/

![obraz](https://user-images.githubusercontent.com/48929607/135799741-fdc7057d-d486-4793-baf2-d0e9cb98acfa.png)

2021-10-04 07:08 UTC, PawelKrawczyk96 commented
On figma icon and Server name is horizontally centered, on project we have alignment to bottom.
![Screenshot from 2021-10-04 09-05-40](https://user-images.githubusercontent.com/37472310/135808086-22ffbb0e-72f4-4569-b681-149d6a0a0400.png)

2021-10-04 08:29 UTC, wojciech-cichocki requested changes
Add details also to Synthetics

2021-10-04 08:59 UTC, awojciak approved these changes

2021-10-04 09:00 UTC, merged