fixes on staking after tests
Synthetify/synthetify-webapp pull request #52
Opened 2021-07-06 12:41 UTC by awojciak

2021-07-06 22:27 UTC, wojciech-cichocki requested changes

2021-07-06 22:27 UTC, wojciech-cichocki commented on src/components/Cards/ValueCard.tsx
>  import useStyles from './style'
`useStyles` should be the last import

2021-07-06 22:27 UTC, wojciech-cichocki commented on src/components/WrappedActionMenu/ActionTemplate/style.ts
>      minHeight: 200,
now rewards tab are slightly longer than other tabs

2021-07-07 06:24 UTC, awojciak commented on src/components/Cards/ValueCard.tsx
>  import useStyles from './style'
przeniesione

2021-07-07 06:24 UTC, awojciak commented on src/components/WrappedActionMenu/ActionTemplate/style.ts
>      minHeight: 200,
już naprawione

2021-07-07 06:26 UTC, wojciech-cichocki approved these changes

2021-07-07 06:35 UTC, merged