updated everything
Synthetify/synthetify-webapp pull request #68
Opened 2021-07-15 17:16 UTC by matzayonc

2021-07-15 23:48 UTC, wojciech-cichocki approved these changes

2021-07-16 06:03 UTC, awojciak requested changes

2021-07-16 06:03 UTC, awojciak commented on package.json
> +    "animated-number-react": "^0.1.2",
tu bym się wstrzymał, w wyższej wersji jest jakiś bug, przez który animacja nie zaczyna się od poprzedniej liczby, ale od zera

2021-07-16 07:28 UTC, matzayonc commented on package.json
> +    "animated-number-react": "^0.1.2",
fixed

2021-07-16 07:28 UTC, merged